export const ActionTypes = {
  ADD_GRATITUDE_ITEM: 'ADD_GRATITUDE_ITEM',
  DELETE_GRATITUDE_ITEM: 'DELETE_GRATITUDE_ITEM',
  EDIT_GRATITUDE_ITEM: 'EDIT_GRATITUDE_ITEM',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  SET_TAB_VALUE: 'SET_TAB_VALUE',
}