export const ActionTypes = {
  // Application reducer
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  SET_TAB_VALUE: 'SET_TAB_VALUE',

  // Gratitude reducer
  ADD_GRATITUDE_ITEM: 'ADD_GRATITUDE_ITEM',
  // DELETE_GRATITUDE_ITEM: 'DELETE_GRATITUDE_ITEM',
  // EDIT_GRATITUDE_ITEM: 'EDIT_GRATITUDE_ITEM',

  // Items reducer
  TOGGLE_ITEM_COMPLETE: 'TOGGLE_ITEM_COMPLETE'
  
}